"""Add quadclass columns and indexes

Revision ID: db1a2ca65d60
Revises: ce8e184b3d1a
Create Date: 2024-08-13 09:05:28.520539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db1a2ca65d60'
down_revision: Union[str, None] = 'ce8e184b3d1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relations', sa.Column('num_verbal_coop', sa.Integer(), nullable=False))
    op.add_column('relations', sa.Column('num_material_coop', sa.Integer(), nullable=False))
    op.add_column('relations', sa.Column('num_verbal_conf', sa.Integer(), nullable=False))
    op.add_column('relations', sa.Column('num_material_conf', sa.Integer(), nullable=False))
    op.create_index('idx_countrya_countryb_date', 'relations', ['country_code_a', 'country_code_b', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_countrya_countryb_date', table_name='relations')
    op.drop_column('relations', 'num_material_conf')
    op.drop_column('relations', 'num_verbal_conf')
    op.drop_column('relations', 'num_material_coop')
    op.drop_column('relations', 'num_verbal_coop')
    # ### end Alembic commands ###
