version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 54329:5432
    volumes:
      - gdelt_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DOCKER_DB_USER}
      - POSTGRES_PASSWORD=${DOCKER_DB_PASSWORD}
      - POSTGRES_DB=${DOCKER_DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DOCKER_DB_USER}" ]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  gdelt_data: