"""Add relations model

Revision ID: ce8e184b3d1a
Revises: 
Create Date: 2024-08-12 10:16:02.661661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce8e184b3d1a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relations',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('country_code_a', sa.CHAR(length=3), nullable=False),
    sa.Column('country_code_b', sa.CHAR(length=3), nullable=False),
    sa.Column('relations_score', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('date', 'country_code_a', 'country_code_b')
    )
    op.create_index('idx_countrya_countryb', 'relations', ['country_code_a', 'country_code_b'], unique=False)
    op.create_index('idx_countrya_date', 'relations', ['country_code_a', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_countrya_date', table_name='relations')
    op.drop_index('idx_countrya_countryb', table_name='relations')
    op.drop_table('relations')
    # ### end Alembic commands ###
