FROM python:3.12

WORKDIR /app

COPY poetry.lock /app/
COPY pyproject.toml /app/

RUN pip install poetry

RUN poetry config virtualenvs.create false
RUN poetry install --no-root --without dev

COPY /src/frontend /app/frontend

EXPOSE 8501

CMD ["python", "-m", "streamlit", "run", "frontend/main.py"]
