version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 54329:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DOCKER_DB_USER}
      - POSTGRES_PASSWORD=${DOCKER_DB_PASSWORD}
      - POSTGRES_DB=${DOCKER_DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DOCKER_DB_USER}" ]
      interval: 1s
      timeout: 5s
      retries: 10

  api:
    image: afilipovski/gdelt/backend:main
    container_name: api
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8000:8000
    environment:
      - DB_URI=${DOCKER_DB_URI}
      - MIGRATION_PATH=${DOCKER_MIGRATION_PATH}
    build:
      context: ..
      dockerfile: deploy/Dockerfile.api
      
  watchtower:
    image: containrrr/watchtower
    command: --interval 60 api